version: '3.8'
services:
  main:
    container_name: server
    build:
      context: .
    env_file:
      -   .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command:
      - npm start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: