version: '3'

services:
  meetup:
    container_name: meetup
    build:
      context: ./meetup
    ports:
      - "5000:5000"
    depends_on:
      - auth
    env_file:
      - ./meetup/.env
    networks:
      - mynetwork

  auth:
    container_name: auth
    build:
      context: ./auth
    ports:
      - "4000:4000"
    env_file:
      - ./auth/.env
    networks:
      - mynetwork


networks:
  mynetwork: