version: '3'

services:
  auth:
    build: ./auth
    ports:
      - '3000:3000'
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:9092

  meetup:
    build: ./meetup
    ports:
      - '4000:4000'
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka:9092

  kafka:
    image: wurstmeister/kafka
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: 'auth-events:1:1'